# utils/constants.py

SUPPORTED_IMAGE_FORMATS = ['.png', '.xpm', '.jpg', '.jpeg', '.bmp', '.gif']
FAVORITES_FILE = "favorites.json"

UNIFORM_HEIGHT = 150
COLUMNS = 5
SPACING_X = 10
SPACING_Y = 10
EDGE_RESIZE_MARGIN = 20
INFINITE_CANVAS_SIZE = 10_000_000
RIGHT_CLICK_DRAG_THRESHOLD = 5
